# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\dlg_mod_input.ui'
#
# Created: Thu Oct 25 16:10:45 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_modifierInputDialog(object):
    def setupUi(self, modifierInputDialog):
        modifierInputDialog.setObjectName(_fromUtf8("modifierInputDialog"))
        modifierInputDialog.resize(449, 365)
        self.lb_ms_zone = QtGui.QLabel(modifierInputDialog)
        self.lb_ms_zone.setGeometry(QtCore.QRect(10, 50, 181, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_ms_zone.setFont(font)
        self.lb_ms_zone.setObjectName(_fromUtf8("lb_ms_zone"))
        self.lb_mod_values = QtGui.QLabel(modifierInputDialog)
        self.lb_mod_values.setGeometry(QtCore.QRect(200, 50, 201, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_mod_values.setFont(font)
        self.lb_mod_values.setObjectName(_fromUtf8("lb_mod_values"))
        self.lb_level1 = QtGui.QLabel(modifierInputDialog)
        self.lb_level1.setGeometry(QtCore.QRect(9, 121, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_level1.setFont(font)
        self.lb_level1.setObjectName(_fromUtf8("lb_level1"))
        self.lb_level3 = QtGui.QLabel(modifierInputDialog)
        self.lb_level3.setGeometry(QtCore.QRect(9, 251, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_level3.setFont(font)
        self.lb_level3.setObjectName(_fromUtf8("lb_level3"))
        self.lb_level2 = QtGui.QLabel(modifierInputDialog)
        self.lb_level2.setGeometry(QtCore.QRect(9, 181, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_level2.setFont(font)
        self.lb_level2.setObjectName(_fromUtf8("lb_level2"))
        self.cb_ms_zone = QtGui.QComboBox(modifierInputDialog)
        self.cb_ms_zone.setGeometry(QtCore.QRect(10, 70, 151, 31))
        self.cb_ms_zone.setObjectName(_fromUtf8("cb_ms_zone"))
        self.cb_level1 = QtGui.QComboBox(modifierInputDialog)
        self.cb_level1.setGeometry(QtCore.QRect(10, 140, 151, 31))
        self.cb_level1.setObjectName(_fromUtf8("cb_level1"))
        self.cb_level2 = QtGui.QComboBox(modifierInputDialog)
        self.cb_level2.setGeometry(QtCore.QRect(10, 200, 151, 31))
        self.cb_level2.setObjectName(_fromUtf8("cb_level2"))
        self.cb_level3 = QtGui.QComboBox(modifierInputDialog)
        self.cb_level3.setGeometry(QtCore.QRect(10, 270, 151, 31))
        self.cb_level3.setObjectName(_fromUtf8("cb_level3"))
        self.table_mod_values = QtGui.QTableView(modifierInputDialog)
        self.table_mod_values.setGeometry(QtCore.QRect(200, 70, 220, 231))
        self.table_mod_values.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_mod_values.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_mod_values.setObjectName(_fromUtf8("table_mod_values"))
        self.btn_mod_build = QtGui.QPushButton(modifierInputDialog)
        self.btn_mod_build.setGeometry(QtCore.QRect(180, 320, 75, 23))
        self.btn_mod_build.setObjectName(_fromUtf8("btn_mod_build"))
        self.btn_apply = QtGui.QPushButton(modifierInputDialog)
        self.btn_apply.setGeometry(QtCore.QRect(260, 320, 75, 23))
        self.btn_apply.setObjectName(_fromUtf8("btn_apply"))
        self.btn_cancel = QtGui.QPushButton(modifierInputDialog)
        self.btn_cancel.setGeometry(QtCore.QRect(340, 320, 75, 23))
        self.btn_cancel.setObjectName(_fromUtf8("btn_cancel"))
        self.lb_title = QtGui.QLabel(modifierInputDialog)
        self.lb_title.setGeometry(QtCore.QRect(10, 10, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lb_title.setFont(font)
        self.lb_title.setObjectName(_fromUtf8("lb_title"))
        self.btn_add = QtGui.QPushButton(modifierInputDialog)
        self.btn_add.setGeometry(QtCore.QRect(360, 40, 31, 23))
        self.btn_add.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon)
        self.btn_add.setObjectName(_fromUtf8("btn_add"))
        self.btn_delete = QtGui.QPushButton(modifierInputDialog)
        self.btn_delete.setGeometry(QtCore.QRect(390, 40, 31, 23))
        self.btn_delete.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/icons/minus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon1)
        self.btn_delete.setObjectName(_fromUtf8("btn_delete"))

        self.retranslateUi(modifierInputDialog)
        QtCore.QObject.connect(self.cb_level1, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), modifierInputDialog.level1Selected)
        QtCore.QObject.connect(self.cb_level2, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), modifierInputDialog.level2Selected)
        QtCore.QObject.connect(self.cb_level3, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), modifierInputDialog.level3Selected)
        QtCore.QObject.connect(self.btn_mod_build, QtCore.SIGNAL(_fromUtf8("clicked()")), modifierInputDialog.buildFromSurvey)
        QtCore.QObject.connect(self.btn_apply, QtCore.SIGNAL(_fromUtf8("clicked()")), modifierInputDialog.setModifier)
        QtCore.QObject.connect(self.btn_cancel, QtCore.SIGNAL(_fromUtf8("clicked()")), modifierInputDialog.reject)
        QtCore.QObject.connect(self.cb_ms_zone, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), modifierInputDialog.zoneSelected)
        QtCore.QObject.connect(self.btn_add, QtCore.SIGNAL(_fromUtf8("clicked()")), modifierInputDialog.addValue)
        QtCore.QObject.connect(self.btn_delete, QtCore.SIGNAL(_fromUtf8("clicked()")), modifierInputDialog.deleteValue)
        QtCore.QMetaObject.connectSlotsByName(modifierInputDialog)

    def retranslateUi(self, modifierInputDialog):
        modifierInputDialog.setWindowTitle(QtGui.QApplication.translate("modifierInputDialog", "Secondary Modifier Input", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ms_zone.setText(QtGui.QApplication.translate("modifierInputDialog", "Zone", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_mod_values.setText(QtGui.QApplication.translate("modifierInputDialog", "Values", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_level1.setText(QtGui.QApplication.translate("modifierInputDialog", "1st level", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_level3.setText(QtGui.QApplication.translate("modifierInputDialog", "3rd level", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_level2.setText(QtGui.QApplication.translate("modifierInputDialog", "2nd level", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_mod_build.setText(QtGui.QApplication.translate("modifierInputDialog", "from Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_apply.setText(QtGui.QApplication.translate("modifierInputDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("modifierInputDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_title.setText(QtGui.QApplication.translate("modifierInputDialog", "Edit Mapping Scheme Branch", None, QtGui.QApplication.UnicodeUTF8))

import SIDDResource_rc
