# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\wdg_ms.ui'
#
# Created: Wed Oct 24 17:25:21 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_widgetMappingSchemes(object):
    def setupUi(self, widgetMappingSchemes):
        widgetMappingSchemes.setObjectName(_fromUtf8("widgetMappingSchemes"))
        widgetMappingSchemes.resize(935, 684)
        self.btn_secondary_mod = QtGui.QPushButton(widgetMappingSchemes)
        self.btn_secondary_mod.setGeometry(QtCore.QRect(640, 630, 131, 31))
        self.btn_secondary_mod.setObjectName(_fromUtf8("btn_secondary_mod"))
        self.btn_build_exposure = QtGui.QPushButton(widgetMappingSchemes)
        self.btn_build_exposure.setGeometry(QtCore.QRect(780, 630, 131, 31))
        self.btn_build_exposure.setObjectName(_fromUtf8("btn_build_exposure"))
        self.tree_ms = QtGui.QTreeView(widgetMappingSchemes)
        self.tree_ms.setGeometry(QtCore.QRect(10, 80, 331, 531))
        self.tree_ms.setObjectName(_fromUtf8("tree_ms"))
        self.btn_create_ms = QtGui.QPushButton(widgetMappingSchemes)
        self.btn_create_ms.setGeometry(QtCore.QRect(170, 50, 31, 23))
        self.btn_create_ms.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/icons/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_create_ms.setIcon(icon)
        self.btn_create_ms.setObjectName(_fromUtf8("btn_create_ms"))
        self.box_library = QtGui.QGroupBox(widgetMappingSchemes)
        self.box_library.setEnabled(True)
        self.box_library.setGeometry(QtCore.QRect(380, 70, 531, 551))
        self.box_library.setObjectName(_fromUtf8("box_library"))
        self.list_ms_library_regions = QtGui.QListWidget(self.box_library)
        self.list_ms_library_regions.setGeometry(QtCore.QRect(320, 40, 200, 191))
        self.list_ms_library_regions.setObjectName(_fromUtf8("list_ms_library_regions"))
        self.lb_ms_library_regions = QtGui.QLabel(self.box_library)
        self.lb_ms_library_regions.setGeometry(QtCore.QRect(320, 20, 200, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_ms_library_regions.setFont(font)
        self.lb_ms_library_regions.setObjectName(_fromUtf8("lb_ms_library_regions"))
        self.lb_ms_library_types = QtGui.QLabel(self.box_library)
        self.lb_ms_library_types.setGeometry(QtCore.QRect(320, 240, 200, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_ms_library_types.setFont(font)
        self.lb_ms_library_types.setObjectName(_fromUtf8("lb_ms_library_types"))
        self.list_ms_library_types = QtGui.QListWidget(self.box_library)
        self.list_ms_library_types.setGeometry(QtCore.QRect(320, 260, 200, 81))
        self.list_ms_library_types.setObjectName(_fromUtf8("list_ms_library_types"))
        self.list_ms_library_msnames = QtGui.QListWidget(self.box_library)
        self.list_ms_library_msnames.setGeometry(QtCore.QRect(320, 380, 200, 151))
        self.list_ms_library_msnames.setObjectName(_fromUtf8("list_ms_library_msnames"))
        self.lb_ms_library_msnames = QtGui.QLabel(self.box_library)
        self.lb_ms_library_msnames.setGeometry(QtCore.QRect(320, 350, 200, 25))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_ms_library_msnames.setFont(font)
        self.lb_ms_library_msnames.setObjectName(_fromUtf8("lb_ms_library_msnames"))
        self.tree_ms_library = QtGui.QTreeView(self.box_library)
        self.tree_ms_library.setGeometry(QtCore.QRect(20, 40, 280, 321))
        self.tree_ms_library.setObjectName(_fromUtf8("tree_ms_library"))
        self.lb_tree_ms_library = QtGui.QLabel(self.box_library)
        self.lb_tree_ms_library.setGeometry(QtCore.QRect(20, 20, 280, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_tree_ms_library.setFont(font)
        self.lb_tree_ms_library.setObjectName(_fromUtf8("lb_tree_ms_library"))
        self.lb_ms_library_date = QtGui.QLabel(self.box_library)
        self.lb_ms_library_date.setGeometry(QtCore.QRect(20, 370, 100, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_ms_library_date.setFont(font)
        self.lb_ms_library_date.setObjectName(_fromUtf8("lb_ms_library_date"))
        self.lb_ms_library_notes = QtGui.QLabel(self.box_library)
        self.lb_ms_library_notes.setGeometry(QtCore.QRect(20, 460, 100, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_ms_library_notes.setFont(font)
        self.lb_ms_library_notes.setObjectName(_fromUtf8("lb_ms_library_notes"))
        self.txt_ms_library_date = QtGui.QLineEdit(self.box_library)
        self.txt_ms_library_date.setGeometry(QtCore.QRect(130, 370, 171, 20))
        self.txt_ms_library_date.setReadOnly(True)
        self.txt_ms_library_date.setObjectName(_fromUtf8("txt_ms_library_date"))
        self.txt_ms_library_notes = QtGui.QTextEdit(self.box_library)
        self.txt_ms_library_notes.setGeometry(QtCore.QRect(130, 460, 171, 71))
        self.txt_ms_library_notes.setReadOnly(True)
        self.txt_ms_library_notes.setObjectName(_fromUtf8("txt_ms_library_notes"))
        self.txt_ms_library_datasource = QtGui.QLineEdit(self.box_library)
        self.txt_ms_library_datasource.setGeometry(QtCore.QRect(130, 400, 171, 20))
        self.txt_ms_library_datasource.setReadOnly(True)
        self.txt_ms_library_datasource.setObjectName(_fromUtf8("txt_ms_library_datasource"))
        self.lb_ms_library_datasource = QtGui.QLabel(self.box_library)
        self.lb_ms_library_datasource.setGeometry(QtCore.QRect(20, 400, 100, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_ms_library_datasource.setFont(font)
        self.lb_ms_library_datasource.setObjectName(_fromUtf8("lb_ms_library_datasource"))
        self.lb_ms_library_quality = QtGui.QLabel(self.box_library)
        self.lb_ms_library_quality.setGeometry(QtCore.QRect(20, 430, 100, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_ms_library_quality.setFont(font)
        self.lb_ms_library_quality.setObjectName(_fromUtf8("lb_ms_library_quality"))
        self.txt_ms_library_quality = QtGui.QLineEdit(self.box_library)
        self.txt_ms_library_quality.setGeometry(QtCore.QRect(130, 430, 171, 21))
        self.txt_ms_library_quality.setReadOnly(True)
        self.txt_ms_library_quality.setObjectName(_fromUtf8("txt_ms_library_quality"))
        self.lb_ms_library_ms = QtGui.QLabel(self.box_library)
        self.lb_ms_library_ms.setGeometry(QtCore.QRect(20, 20, 100, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_ms_library_ms.setFont(font)
        self.lb_ms_library_ms.setObjectName(_fromUtf8("lb_ms_library_ms"))
        self.btn_del_lib_ms = QtGui.QPushButton(self.box_library)
        self.btn_del_lib_ms.setGeometry(QtCore.QRect(490, 350, 31, 25))
        self.btn_del_lib_ms.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/icons/minus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_del_lib_ms.setIcon(icon1)
        self.btn_del_lib_ms.setObjectName(_fromUtf8("btn_del_lib_ms"))
        self.btn_save_ms = QtGui.QPushButton(widgetMappingSchemes)
        self.btn_save_ms.setGeometry(QtCore.QRect(200, 50, 31, 23))
        self.btn_save_ms.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save_ms.setIcon(icon2)
        self.btn_save_ms.setObjectName(_fromUtf8("btn_save_ms"))
        self.btn_del_child = QtGui.QPushButton(widgetMappingSchemes)
        self.btn_del_child.setGeometry(QtCore.QRect(280, 50, 31, 23))
        self.btn_del_child.setText(_fromUtf8(""))
        self.btn_del_child.setIcon(icon1)
        self.btn_del_child.setObjectName(_fromUtf8("btn_del_child"))
        self.btn_edit_level = QtGui.QPushButton(widgetMappingSchemes)
        self.btn_edit_level.setGeometry(QtCore.QRect(310, 50, 31, 23))
        self.btn_edit_level.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit_level.setIcon(icon3)
        self.btn_edit_level.setObjectName(_fromUtf8("btn_edit_level"))
        self.lb_panel_title = QtGui.QLabel(widgetMappingSchemes)
        self.lb_panel_title.setGeometry(QtCore.QRect(10, 10, 891, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lb_panel_title.setFont(font)
        self.lb_panel_title.setObjectName(_fromUtf8("lb_panel_title"))
        self.btn_add_child = QtGui.QPushButton(widgetMappingSchemes)
        self.btn_add_child.setGeometry(QtCore.QRect(250, 50, 31, 23))
        self.btn_add_child.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_child.setIcon(icon4)
        self.btn_add_child.setObjectName(_fromUtf8("btn_add_child"))
        self.btn_add_branch = QtGui.QPushButton(widgetMappingSchemes)
        self.btn_add_branch.setGeometry(QtCore.QRect(350, 200, 31, 23))
        self.btn_add_branch.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/icons/arrow_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_branch.setIcon(icon5)
        self.btn_add_branch.setObjectName(_fromUtf8("btn_add_branch"))
        self.btn_build_ms = QtGui.QPushButton(widgetMappingSchemes)
        self.btn_build_ms.setGeometry(QtCore.QRect(10, 50, 31, 23))
        self.btn_build_ms.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/imgs/icons/magnify.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_build_ms.setIcon(icon6)
        self.btn_build_ms.setObjectName(_fromUtf8("btn_build_ms"))
        self.ck_enable_ms_library = QtGui.QCheckBox(widgetMappingSchemes)
        self.ck_enable_ms_library.setGeometry(QtCore.QRect(390, 50, 251, 17))
        self.ck_enable_ms_library.setObjectName(_fromUtf8("ck_enable_ms_library"))

        self.retranslateUi(widgetMappingSchemes)
        QtCore.QObject.connect(self.btn_build_ms, QtCore.SIGNAL(_fromUtf8("clicked()")), widgetMappingSchemes.buildMS)
        QtCore.QObject.connect(self.btn_create_ms, QtCore.SIGNAL(_fromUtf8("clicked()")), widgetMappingSchemes.createMS)
        QtCore.QObject.connect(self.btn_save_ms, QtCore.SIGNAL(_fromUtf8("clicked()")), widgetMappingSchemes.saveMS)
        QtCore.QObject.connect(self.btn_add_child, QtCore.SIGNAL(_fromUtf8("clicked()")), widgetMappingSchemes.addBranch)
        QtCore.QObject.connect(self.btn_del_child, QtCore.SIGNAL(_fromUtf8("clicked()")), widgetMappingSchemes.removeBranch)
        QtCore.QObject.connect(self.btn_edit_level, QtCore.SIGNAL(_fromUtf8("clicked()")), widgetMappingSchemes.editBranch)
        QtCore.QObject.connect(self.btn_add_branch, QtCore.SIGNAL(_fromUtf8("clicked()")), widgetMappingSchemes.appendBranch)
        QtCore.QObject.connect(self.btn_secondary_mod, QtCore.SIGNAL(_fromUtf8("clicked()")), widgetMappingSchemes.setModifiers)
        QtCore.QObject.connect(self.btn_build_exposure, QtCore.SIGNAL(_fromUtf8("clicked()")), widgetMappingSchemes.applyMS)
        QtCore.QObject.connect(self.list_ms_library_regions, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), widgetMappingSchemes.regionSelected)
        QtCore.QObject.connect(self.list_ms_library_types, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), widgetMappingSchemes.typeSelected)
        QtCore.QObject.connect(self.list_ms_library_msnames, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), widgetMappingSchemes.msSelected)
        QtCore.QObject.connect(self.ck_enable_ms_library, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), widgetMappingSchemes.toggleMSLibrary)
        QtCore.QObject.connect(self.btn_del_lib_ms, QtCore.SIGNAL(_fromUtf8("clicked()")), widgetMappingSchemes.deleteLibraryMS)
        QtCore.QMetaObject.connectSlotsByName(widgetMappingSchemes)

    def retranslateUi(self, widgetMappingSchemes):
        widgetMappingSchemes.setWindowTitle(QtGui.QApplication.translate("widgetMappingSchemes", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_secondary_mod.setText(QtGui.QApplication.translate("widgetMappingSchemes", "Secondary Modifiers", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_build_exposure.setText(QtGui.QApplication.translate("widgetMappingSchemes", "Apply Mapping Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.box_library.setTitle(QtGui.QApplication.translate("widgetMappingSchemes", "Mapping Schemes", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ms_library_regions.setText(QtGui.QApplication.translate("widgetMappingSchemes", "Regions", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ms_library_types.setText(QtGui.QApplication.translate("widgetMappingSchemes", "Types", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ms_library_msnames.setText(QtGui.QApplication.translate("widgetMappingSchemes", "Available Mapping Schemes", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ms_library_date.setText(QtGui.QApplication.translate("widgetMappingSchemes", "Date Created", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ms_library_notes.setText(QtGui.QApplication.translate("widgetMappingSchemes", "Use Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ms_library_datasource.setText(QtGui.QApplication.translate("widgetMappingSchemes", "Data Source", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ms_library_quality.setText(QtGui.QApplication.translate("widgetMappingSchemes", "Percentage of", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_ms_library_ms.setText(QtGui.QApplication.translate("widgetMappingSchemes", "Use Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_panel_title.setText(QtGui.QApplication.translate("widgetMappingSchemes", "Assign Mapping Schemes", None, QtGui.QApplication.UnicodeUTF8))
        self.ck_enable_ms_library.setText(QtGui.QApplication.translate("widgetMappingSchemes", "Enable MS Library", None, QtGui.QApplication.UnicodeUTF8))

import SIDDResource_rc
