# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\wdg_data_wizard.ui'
#
# Created: Mon Apr 29 16:47:36 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_widgetDataWizard(object):
    def setupUi(self, widgetDataWizard):
        widgetDataWizard.setObjectName(_fromUtf8("widgetDataWizard"))
        widgetDataWizard.resize(776, 410)
        widgetDataWizard.setModal(True)
        widgetDataWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.wizardPageZones = QtGui.QWizardPage()
        self.wizardPageZones.setObjectName(_fromUtf8("wizardPageZones"))
        self.widgetZones = QtGui.QWidget(self.wizardPageZones)
        self.widgetZones.setGeometry(QtCore.QRect(10, 10, 411, 291))
        self.widgetZones.setObjectName(_fromUtf8("widgetZones"))
        self.radio_zones_count = QtGui.QRadioButton(self.widgetZones)
        self.radio_zones_count.setGeometry(QtCore.QRect(10, 70, 391, 17))
        self.radio_zones_count.setObjectName(_fromUtf8("radio_zones_count"))
        self.radio_zones_only = QtGui.QRadioButton(self.widgetZones)
        self.radio_zones_only.setGeometry(QtCore.QRect(10, 50, 391, 17))
        self.radio_zones_only.setObjectName(_fromUtf8("radio_zones_only"))
        self.lb_zones_proj = QtGui.QLabel(self.widgetZones)
        self.lb_zones_proj.setGeometry(QtCore.QRect(10, 240, 151, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_zones_proj.setFont(font)
        self.lb_zones_proj.setObjectName(_fromUtf8("lb_zones_proj"))
        self.lb_zones_select_file = QtGui.QLabel(self.widgetZones)
        self.lb_zones_select_file.setGeometry(QtCore.QRect(10, 95, 71, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_zones_select_file.setFont(font)
        self.lb_zones_select_file.setObjectName(_fromUtf8("lb_zones_select_file"))
        self.radio_zones_no_data = QtGui.QRadioButton(self.widgetZones)
        self.radio_zones_no_data.setGeometry(QtCore.QRect(10, 30, 391, 17))
        self.radio_zones_no_data.setChecked(True)
        self.radio_zones_no_data.setObjectName(_fromUtf8("radio_zones_no_data"))
        self.cb_zones_class_field = QtGui.QComboBox(self.widgetZones)
        self.cb_zones_class_field.setEnabled(False)
        self.cb_zones_class_field.setGeometry(QtCore.QRect(10, 170, 171, 22))
        self.cb_zones_class_field.setObjectName(_fromUtf8("cb_zones_class_field"))
        self.lb_zones_class_field = QtGui.QLabel(self.widgetZones)
        self.lb_zones_class_field.setGeometry(QtCore.QRect(10, 146, 281, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_zones_class_field.setFont(font)
        self.lb_zones_class_field.setObjectName(_fromUtf8("lb_zones_class_field"))
        self.btn_zones_select_file = QtGui.QToolButton(self.widgetZones)
        self.btn_zones_select_file.setEnabled(False)
        self.btn_zones_select_file.setGeometry(QtCore.QRect(380, 121, 21, 21))
        self.btn_zones_select_file.setCursor(QtCore.Qt.ArrowCursor)
        self.btn_zones_select_file.setObjectName(_fromUtf8("btn_zones_select_file"))
        self.cb_zones_proj = QtGui.QComboBox(self.widgetZones)
        self.cb_zones_proj.setEnabled(False)
        self.cb_zones_proj.setGeometry(QtCore.QRect(10, 260, 171, 22))
        self.cb_zones_proj.setObjectName(_fromUtf8("cb_zones_proj"))
        self.txt_zones_select_file = QtGui.QLineEdit(self.widgetZones)
        self.txt_zones_select_file.setEnabled(False)
        self.txt_zones_select_file.setGeometry(QtCore.QRect(10, 120, 361, 20))
        self.txt_zones_select_file.setObjectName(_fromUtf8("txt_zones_select_file"))
        self.lb_zones_desc = QtGui.QLabel(self.widgetZones)
        self.lb_zones_desc.setGeometry(QtCore.QRect(10, 10, 251, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_zones_desc.setFont(font)
        self.lb_zones_desc.setObjectName(_fromUtf8("lb_zones_desc"))
        self.lb_zones_count_field = QtGui.QLabel(self.widgetZones)
        self.lb_zones_count_field.setGeometry(QtCore.QRect(10, 200, 271, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_zones_count_field.setFont(font)
        self.lb_zones_count_field.setObjectName(_fromUtf8("lb_zones_count_field"))
        self.cb_zones_count_field = QtGui.QComboBox(self.widgetZones)
        self.cb_zones_count_field.setEnabled(False)
        self.cb_zones_count_field.setGeometry(QtCore.QRect(10, 220, 171, 22))
        self.cb_zones_count_field.setObjectName(_fromUtf8("cb_zones_count_field"))
        self.txt_zones_desc = QtGui.QTextEdit(self.wizardPageZones)
        self.txt_zones_desc.setGeometry(QtCore.QRect(430, 10, 321, 290))
        self.txt_zones_desc.setObjectName(_fromUtf8("txt_zones_desc"))
        widgetDataWizard.addPage(self.wizardPageZones)
        self.wizardPageFoortprints = QtGui.QWizardPage()
        self.wizardPageFoortprints.setObjectName(_fromUtf8("wizardPageFoortprints"))
        self.widgetFootprint = QtGui.QWidget(self.wizardPageFoortprints)
        self.widgetFootprint.setGeometry(QtCore.QRect(10, 10, 411, 290))
        self.widgetFootprint.setObjectName(_fromUtf8("widgetFootprint"))
        self.cb_fp_story_field = QtGui.QComboBox(self.widgetFootprint)
        self.cb_fp_story_field.setEnabled(False)
        self.cb_fp_story_field.setGeometry(QtCore.QRect(280, 146, 121, 22))
        self.cb_fp_story_field.setObjectName(_fromUtf8("cb_fp_story_field"))
        self.radio_fp_height = QtGui.QRadioButton(self.widgetFootprint)
        self.radio_fp_height.setGeometry(QtCore.QRect(10, 70, 381, 17))
        self.radio_fp_height.setObjectName(_fromUtf8("radio_fp_height"))
        self.txt_fp_select_file = QtGui.QLineEdit(self.widgetFootprint)
        self.txt_fp_select_file.setEnabled(False)
        self.txt_fp_select_file.setGeometry(QtCore.QRect(10, 121, 361, 20))
        self.txt_fp_select_file.setObjectName(_fromUtf8("txt_fp_select_file"))
        self.lb_fp_select_file = QtGui.QLabel(self.widgetFootprint)
        self.lb_fp_select_file.setGeometry(QtCore.QRect(10, 95, 71, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_fp_select_file.setFont(font)
        self.lb_fp_select_file.setObjectName(_fromUtf8("lb_fp_select_file"))
        self.radio_fp_only = QtGui.QRadioButton(self.widgetFootprint)
        self.radio_fp_only.setGeometry(QtCore.QRect(10, 50, 381, 17))
        self.radio_fp_only.setObjectName(_fromUtf8("radio_fp_only"))
        self.lb_fp_desc = QtGui.QLabel(self.widgetFootprint)
        self.lb_fp_desc.setGeometry(QtCore.QRect(10, 10, 305, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_fp_desc.setFont(font)
        self.lb_fp_desc.setObjectName(_fromUtf8("lb_fp_desc"))
        self.cb_fp_proj = QtGui.QComboBox(self.widgetFootprint)
        self.cb_fp_proj.setEnabled(False)
        self.cb_fp_proj.setGeometry(QtCore.QRect(280, 171, 121, 22))
        self.cb_fp_proj.setObjectName(_fromUtf8("cb_fp_proj"))
        self.lb_fp_proj = QtGui.QLabel(self.widgetFootprint)
        self.lb_fp_proj.setGeometry(QtCore.QRect(10, 171, 151, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_fp_proj.setFont(font)
        self.lb_fp_proj.setObjectName(_fromUtf8("lb_fp_proj"))
        self.btn_fp_select_file = QtGui.QToolButton(self.widgetFootprint)
        self.btn_fp_select_file.setEnabled(False)
        self.btn_fp_select_file.setGeometry(QtCore.QRect(380, 121, 21, 21))
        self.btn_fp_select_file.setCursor(QtCore.Qt.ArrowCursor)
        self.btn_fp_select_file.setObjectName(_fromUtf8("btn_fp_select_file"))
        self.radio_fp_no_data = QtGui.QRadioButton(self.widgetFootprint)
        self.radio_fp_no_data.setGeometry(QtCore.QRect(10, 30, 381, 17))
        self.radio_fp_no_data.setChecked(True)
        self.radio_fp_no_data.setObjectName(_fromUtf8("radio_fp_no_data"))
        self.lb_fp_story_field = QtGui.QLabel(self.widgetFootprint)
        self.lb_fp_story_field.setGeometry(QtCore.QRect(10, 146, 241, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_fp_story_field.setFont(font)
        self.lb_fp_story_field.setObjectName(_fromUtf8("lb_fp_story_field"))
        self.txt_fp_desc = QtGui.QTextEdit(self.wizardPageFoortprints)
        self.txt_fp_desc.setGeometry(QtCore.QRect(430, 10, 321, 290))
        self.txt_fp_desc.setObjectName(_fromUtf8("txt_fp_desc"))
        widgetDataWizard.addPage(self.wizardPageFoortprints)
        self.wizardPageSurveys = QtGui.QWizardPage()
        self.wizardPageSurveys.setObjectName(_fromUtf8("wizardPageSurveys"))
        self.widgetSurvey = QtGui.QWidget(self.wizardPageSurveys)
        self.widgetSurvey.setGeometry(QtCore.QRect(10, 10, 411, 290))
        self.widgetSurvey.setObjectName(_fromUtf8("widgetSurvey"))
        self.lb_svy_select_file = QtGui.QLabel(self.widgetSurvey)
        self.lb_svy_select_file.setGeometry(QtCore.QRect(10, 95, 71, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_svy_select_file.setFont(font)
        self.lb_svy_select_file.setObjectName(_fromUtf8("lb_svy_select_file"))
        self.lb_svy_desc = QtGui.QLabel(self.widgetSurvey)
        self.lb_svy_desc.setGeometry(QtCore.QRect(10, 10, 261, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_svy_desc.setFont(font)
        self.lb_svy_desc.setObjectName(_fromUtf8("lb_svy_desc"))
        self.btn_svy_select_file = QtGui.QToolButton(self.widgetSurvey)
        self.btn_svy_select_file.setEnabled(False)
        self.btn_svy_select_file.setGeometry(QtCore.QRect(380, 121, 21, 21))
        self.btn_svy_select_file.setCursor(QtCore.Qt.ArrowCursor)
        self.btn_svy_select_file.setObjectName(_fromUtf8("btn_svy_select_file"))
        self.radio_svy_sampled = QtGui.QRadioButton(self.widgetSurvey)
        self.radio_svy_sampled.setGeometry(QtCore.QRect(10, 50, 381, 17))
        self.radio_svy_sampled.setObjectName(_fromUtf8("radio_svy_sampled"))
        self.radio_svy_no_data = QtGui.QRadioButton(self.widgetSurvey)
        self.radio_svy_no_data.setGeometry(QtCore.QRect(10, 30, 381, 17))
        self.radio_svy_no_data.setChecked(True)
        self.radio_svy_no_data.setObjectName(_fromUtf8("radio_svy_no_data"))
        self.radio_svy_complete = QtGui.QRadioButton(self.widgetSurvey)
        self.radio_svy_complete.setGeometry(QtCore.QRect(10, 70, 381, 17))
        self.radio_svy_complete.setObjectName(_fromUtf8("radio_svy_complete"))
        self.txt_svy_select_file = QtGui.QLineEdit(self.widgetSurvey)
        self.txt_svy_select_file.setEnabled(False)
        self.txt_svy_select_file.setGeometry(QtCore.QRect(10, 121, 361, 20))
        self.txt_svy_select_file.setObjectName(_fromUtf8("txt_svy_select_file"))
        self.txt_survey_desc = QtGui.QTextEdit(self.wizardPageSurveys)
        self.txt_survey_desc.setGeometry(QtCore.QRect(430, 10, 321, 290))
        self.txt_survey_desc.setObjectName(_fromUtf8("txt_survey_desc"))
        widgetDataWizard.addPage(self.wizardPageSurveys)
        self.wizardPageAggr = QtGui.QWizardPage()
        self.wizardPageAggr.setObjectName(_fromUtf8("wizardPageAggr"))
        self.widgetAggr = QtGui.QWidget(self.wizardPageAggr)
        self.widgetAggr.setGeometry(QtCore.QRect(10, 10, 411, 290))
        self.widgetAggr.setObjectName(_fromUtf8("widgetAggr"))
        self.radio_aggr_grid = QtGui.QRadioButton(self.widgetAggr)
        self.radio_aggr_grid.setGeometry(QtCore.QRect(10, 50, 381, 17))
        self.radio_aggr_grid.setChecked(True)
        self.radio_aggr_grid.setObjectName(_fromUtf8("radio_aggr_grid"))
        self.lb_aggr_desc = QtGui.QLabel(self.widgetAggr)
        self.lb_aggr_desc.setGeometry(QtCore.QRect(10, 10, 281, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_aggr_desc.setFont(font)
        self.lb_aggr_desc.setObjectName(_fromUtf8("lb_aggr_desc"))
        self.radio_aggr_zones = QtGui.QRadioButton(self.widgetAggr)
        self.radio_aggr_zones.setGeometry(QtCore.QRect(10, 30, 381, 17))
        self.radio_aggr_zones.setObjectName(_fromUtf8("radio_aggr_zones"))
        self.txt_aggr_desc = QtGui.QTextEdit(self.wizardPageAggr)
        self.txt_aggr_desc.setGeometry(QtCore.QRect(430, 10, 321, 290))
        self.txt_aggr_desc.setObjectName(_fromUtf8("txt_aggr_desc"))
        widgetDataWizard.addPage(self.wizardPageAggr)
        self.wizardPageVerify = QtGui.QWizardPage()
        self.wizardPageVerify.setObjectName(_fromUtf8("wizardPageVerify"))
        self.widgetResult = QtGui.QWidget(self.wizardPageVerify)
        self.widgetResult.setGeometry(QtCore.QRect(10, 10, 411, 290))
        self.widgetResult.setObjectName(_fromUtf8("widgetResult"))
        self.lb_verify_title = QtGui.QLabel(self.widgetResult)
        self.lb_verify_title.setGeometry(QtCore.QRect(10, 10, 301, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_verify_title.setFont(font)
        self.lb_verify_title.setObjectName(_fromUtf8("lb_verify_title"))
        self.img_lb_verify_fp = QtGui.QLabel(self.widgetResult)
        self.img_lb_verify_fp.setGeometry(QtCore.QRect(10, 38, 21, 21))
        self.img_lb_verify_fp.setText(_fromUtf8(""))
        self.img_lb_verify_fp.setObjectName(_fromUtf8("img_lb_verify_fp"))
        self.img_lb_verify_zones = QtGui.QLabel(self.widgetResult)
        self.img_lb_verify_zones.setGeometry(QtCore.QRect(10, 59, 21, 21))
        self.img_lb_verify_zones.setText(_fromUtf8(""))
        self.img_lb_verify_zones.setObjectName(_fromUtf8("img_lb_verify_zones"))
        self.lb_verify_fp = QtGui.QLabel(self.widgetResult)
        self.lb_verify_fp.setGeometry(QtCore.QRect(40, 38, 111, 20))
        self.lb_verify_fp.setObjectName(_fromUtf8("lb_verify_fp"))
        self.lb_verify_svy = QtGui.QLabel(self.widgetResult)
        self.lb_verify_svy.setGeometry(QtCore.QRect(40, 80, 111, 20))
        self.lb_verify_svy.setObjectName(_fromUtf8("lb_verify_svy"))
        self.lb_verify_zones = QtGui.QLabel(self.widgetResult)
        self.lb_verify_zones.setGeometry(QtCore.QRect(40, 59, 111, 20))
        self.lb_verify_zones.setObjectName(_fromUtf8("lb_verify_zones"))
        self.img_lb_verify_svy = QtGui.QLabel(self.widgetResult)
        self.img_lb_verify_svy.setGeometry(QtCore.QRect(10, 80, 21, 21))
        self.img_lb_verify_svy.setText(_fromUtf8(""))
        self.img_lb_verify_svy.setObjectName(_fromUtf8("img_lb_verify_svy"))
        self.lb_verify_aggregation = QtGui.QLabel(self.widgetResult)
        self.lb_verify_aggregation.setGeometry(QtCore.QRect(10, 113, 171, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lb_verify_aggregation.setFont(font)
        self.lb_verify_aggregation.setObjectName(_fromUtf8("lb_verify_aggregation"))
        self.img_lb_verify_agg_grid = QtGui.QLabel(self.widgetResult)
        self.img_lb_verify_agg_grid.setGeometry(QtCore.QRect(10, 150, 21, 21))
        self.img_lb_verify_agg_grid.setText(_fromUtf8(""))
        self.img_lb_verify_agg_grid.setObjectName(_fromUtf8("img_lb_verify_agg_grid"))
        self.img_lb_verify_agg_zone = QtGui.QLabel(self.widgetResult)
        self.img_lb_verify_agg_zone.setGeometry(QtCore.QRect(10, 130, 21, 21))
        self.img_lb_verify_agg_zone.setText(_fromUtf8(""))
        self.img_lb_verify_agg_zone.setObjectName(_fromUtf8("img_lb_verify_agg_zone"))
        self.lb_verify_agg_zone = QtGui.QLabel(self.widgetResult)
        self.lb_verify_agg_zone.setGeometry(QtCore.QRect(40, 130, 131, 20))
        self.lb_verify_agg_zone.setObjectName(_fromUtf8("lb_verify_agg_zone"))
        self.lb_verify_agg_grid = QtGui.QLabel(self.widgetResult)
        self.lb_verify_agg_grid.setGeometry(QtCore.QRect(40, 150, 131, 20))
        self.lb_verify_agg_grid.setObjectName(_fromUtf8("lb_verify_agg_grid"))
        self.txt_verify_text = QtGui.QTextBrowser(self.wizardPageVerify)
        self.txt_verify_text.setGeometry(QtCore.QRect(430, 10, 321, 290))
        self.txt_verify_text.setObjectName(_fromUtf8("txt_verify_text"))
        widgetDataWizard.addPage(self.wizardPageVerify)

        self.retranslateUi(widgetDataWizard)
        QtCore.QMetaObject.connectSlotsByName(widgetDataWizard)

    def retranslateUi(self, widgetDataWizard):
        widgetDataWizard.setWindowTitle(QtGui.QApplication.translate("widgetDataWizard", "Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPageZones.setTitle(QtGui.QApplication.translate("widgetDataWizard", "Zone", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPageZones.setSubTitle(QtGui.QApplication.translate("widgetDataWizard", "Homogenous Zone data", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_zones_count.setText(QtGui.QApplication.translate("widgetDataWizard", "Land use zones with building count", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_zones_only.setText(QtGui.QApplication.translate("widgetDataWizard", "Land use zones", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_zones_proj.setText(QtGui.QApplication.translate("widgetDataWizard", "Select/verify projection:", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_zones_select_file.setText(QtGui.QApplication.translate("widgetDataWizard", "Select file:", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_zones_no_data.setText(QtGui.QApplication.translate("widgetDataWizard", "No Data", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_zones_class_field.setText(QtGui.QApplication.translate("widgetDataWizard", "Select field containing land use/class attributes:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_zones_select_file.setText(QtGui.QApplication.translate("widgetDataWizard", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_zones_desc.setText(QtGui.QApplication.translate("widgetDataWizard", "What type of data do you have for zones?", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_zones_count_field.setText(QtGui.QApplication.translate("widgetDataWizard", "Select field containing building count", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPageFoortprints.setTitle(QtGui.QApplication.translate("widgetDataWizard", "Footprint", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPageFoortprints.setSubTitle(QtGui.QApplication.translate("widgetDataWizard", "Building Footprint Data", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_fp_height.setText(QtGui.QApplication.translate("widgetDataWizard", "Building footprints with height", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_fp_select_file.setText(QtGui.QApplication.translate("widgetDataWizard", "Select file:", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_fp_only.setText(QtGui.QApplication.translate("widgetDataWizard", "Building footprints without height", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_fp_desc.setText(QtGui.QApplication.translate("widgetDataWizard", "What type of data do you have for building footprints?", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_fp_proj.setText(QtGui.QApplication.translate("widgetDataWizard", "Select/verify projection:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fp_select_file.setText(QtGui.QApplication.translate("widgetDataWizard", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_fp_no_data.setText(QtGui.QApplication.translate("widgetDataWizard", "No Data", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_fp_story_field.setText(QtGui.QApplication.translate("widgetDataWizard", "Select field containing number of stories:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPageSurveys.setTitle(QtGui.QApplication.translate("widgetDataWizard", "Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPageSurveys.setSubTitle(QtGui.QApplication.translate("widgetDataWizard", "Field survey data", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_svy_select_file.setText(QtGui.QApplication.translate("widgetDataWizard", "Select file:", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_svy_desc.setText(QtGui.QApplication.translate("widgetDataWizard", "What type of survey / field data do you have?", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_svy_select_file.setText(QtGui.QApplication.translate("widgetDataWizard", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_svy_sampled.setText(QtGui.QApplication.translate("widgetDataWizard", "Sampled buildings from survey area", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_svy_no_data.setText(QtGui.QApplication.translate("widgetDataWizard", "No Data", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_svy_complete.setText(QtGui.QApplication.translate("widgetDataWizard", "Complete building stock/survey area", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPageAggr.setTitle(QtGui.QApplication.translate("widgetDataWizard", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPageAggr.setSubTitle(QtGui.QApplication.translate("widgetDataWizard", "Output Aggregation Format", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_aggr_grid.setText(QtGui.QApplication.translate("widgetDataWizard", "GED Compatible 30 arc-second grid", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_aggr_desc.setText(QtGui.QApplication.translate("widgetDataWizard", "How do you wish to aggregate your output data?", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_aggr_zones.setText(QtGui.QApplication.translate("widgetDataWizard", "Output into defined zones ", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPageVerify.setTitle(QtGui.QApplication.translate("widgetDataWizard", "Review", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPageVerify.setSubTitle(QtGui.QApplication.translate("widgetDataWizard", "Review input data", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_verify_title.setText(QtGui.QApplication.translate("widgetDataWizard", "You have supplied the following types of data:", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_verify_fp.setText(QtGui.QApplication.translate("widgetDataWizard", "Footprint", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_verify_svy.setText(QtGui.QApplication.translate("widgetDataWizard", "Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_verify_zones.setText(QtGui.QApplication.translate("widgetDataWizard", "Zones", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_verify_aggregation.setText(QtGui.QApplication.translate("widgetDataWizard", "With aggregation", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_verify_agg_zone.setText(QtGui.QApplication.translate("widgetDataWizard", "Zone", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_verify_agg_grid.setText(QtGui.QApplication.translate("widgetDataWizard", "GED Compatible Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_verify_text.setHtml(QtGui.QApplication.translate("widgetDataWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import SIDDResource_rc
